<a href="https://colab.research.google.com/github/keithferns98/ML/blob/main/chisquare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import scipy.stats as stats


In [2]:
import seaborn as sns
import pandas as pd
import numpy as np


In [3]:
dataset=sns.load_dataset('tips')


In [4]:
dataset.head(10)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [5]:
dataset.shape

(244, 7)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.3 KB


In [7]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [8]:
#observed Values
Observed_Values=dataset_table.values
print('Observed Values:-\n',Observed_Values)

Observed Values:-
 [[60 97]
 [33 54]]


In [9]:
val=stats.chi2_contingency(dataset_table)

In [10]:
val

(0.008763290531773594, 0.925417020494423, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [11]:
val[3]

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [12]:
len(dataset_table.iloc[0:2,0])

2

In [24]:
Expected_values=val[3]
Expected_values.shape

(2, 2)

In [14]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
dof=(no_of_rows-1)*(no_of_columns-1)
print('Degree of freedom',dof)
alpha=0.05

Degree of freedom 1


In [20]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(Observed_Values,Expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [25]:
chi_square

array([0.00119737, 0.00073745])

In [22]:
print('chi-square statistics:-',chi_square_statistic)

chi-square statistics:- 0.001934818536627623


In [26]:
critical_value=chi2.ppf(q=1-alpha,df=dof)
print('critical_val',critical_value)

critical_val 3.841458820694124


In [28]:
p_value=chi2.cdf(x=chi_square_statistic,df=dof)
print('p-value',p_value)
print('Significancelevel',alpha)
print('Degree of Freedom',dof)


p-value 0.03508489268426801
Significancelevel 0.05
Degree of Freedom 1


In [29]:
if chi_square_statistic>=critical_value:
  print('Reject H0,There is a relationship between 2 categorical cols')
else:
  print('Reject H0,There is no relationship between 2 categorical cols')

if p_value<=alpha:
  print('Reject H0,Theres is a relationship between 2 cat cols')
else:
  print('Reject H0,There is no relationship between 2 categorical cols')


Reject H0,There is no relationship between 2 categorical cols
Reject H0,Theres is a relationship between 2 cat cols
