<a href="https://colab.research.google.com/github/keithferns98/ML/blob/main/ML_parkinson'sdisease(XGboost).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('parkinsons.data')


In [4]:
df.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0  phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1  phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2  phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3  phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4  phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335

[5 rows x 24 columns]

Splitting the data into features and labels ie
features = all columns and not status
target= status

In [7]:
feature_cols=  [val for val in df.columns if val not in ['name','stats']]
features=df.loc[:,feature_cols].values
labels=df.loc[:,'status'].values

In [8]:
feature_cols

['MDVP:Fo(Hz)',
 'MDVP:Fhi(Hz)',
 'MDVP:Flo(Hz)',
 'MDVP:Jitter(%)',
 'MDVP:Jitter(Abs)',
 'MDVP:RAP',
 'MDVP:PPQ',
 'Jitter:DDP',
 'MDVP:Shimmer',
 'MDVP:Shimmer(dB)',
 'Shimmer:APQ3',
 'Shimmer:APQ5',
 'MDVP:APQ',
 'Shimmer:DDA',
 'NHR',
 'HNR',
 'status',
 'RPDE',
 'DFA',
 'spread1',
 'spread2',
 'D2',
 'PPE']

In [9]:
features

array([[1.199920e+02, 1.573020e+02, 7.499700e+01, ..., 2.664820e-01,
        2.301442e+00, 2.846540e-01],
       [1.224000e+02, 1.486500e+02, 1.138190e+02, ..., 3.355900e-01,
        2.486855e+00, 3.686740e-01],
       [1.166820e+02, 1.311110e+02, 1.115550e+02, ..., 3.111730e-01,
        2.342259e+00, 3.326340e-01],
       ...,
       [1.746880e+02, 2.400050e+02, 7.428700e+01, ..., 1.584530e-01,
        2.679772e+00, 1.317280e-01],
       [1.987640e+02, 3.969610e+02, 7.490400e+01, ..., 2.074540e-01,
        2.138608e+00, 1.233060e-01],
       [2.142890e+02, 2.602770e+02, 7.797300e+01, ..., 1.906670e-01,
        2.555477e+00, 1.485690e-01]])

In [11]:
labels_freq={}
for val in list(set(labels)):
  labels_freq[val]=0
  for label in labels:
      if label==val:
        labels_freq[val]+=1


In [12]:
labels_freq

{0: 48, 1: 147}

In [14]:
scaler=MinMaxScaler((-1,1))
X=scaler.fit_transform(features)

In [15]:
y=labels

#Splittin the dataset into trainin and testing with 80% training and 20% testing

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=7)

In [17]:
#Intialize the xgbclassifier and train the model
model=XGBClassifier()
model.fit(X_train,y_train,eval_metric="error")

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [19]:
y_pred=model.predict(X_test)

In [23]:
acc_scr=accuracy_score(y_test,y_pred)*100

In [24]:
acc_scr


100.0

In [25]:
y_pred==y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [26]:
X_test

array([[ 4.10975013e-01, -3.84051359e-01, -7.23513766e-01,
        -7.48411690e-01, -8.18181818e-01, -7.46628131e-01,
        -7.85637728e-01, -7.46347728e-01, -6.71900676e-01,
        -7.07477403e-01, -5.57395994e-01, -7.05020353e-01,
        -8.22344743e-01, -5.57324432e-01, -8.88913645e-01,
        -1.29805738e-01, -1.00000000e+00, -1.82866249e-01,
        -1.31797646e-01, -3.60088939e-01, -4.46088528e-01,
         2.10947440e-01, -4.84884887e-01],
       [-5.27198845e-01,  5.41390326e-01, -7.37757205e-01,
        -7.37611182e-01, -6.60079051e-01, -8.33333333e-01,
        -7.62057878e-01, -8.33360090e-01, -8.07558883e-01,
        -7.76499589e-01, -8.48228043e-01, -8.51560380e-01,
        -8.44551650e-01, -8.47990756e-01, -8.54537352e-01,
         3.25042673e-01,  1.00000000e+00,  7.88439058e-02,
        -1.24738054e-01, -3.56763292e-01,  2.32090478e-01,
         1.23689647e-01, -5.53095512e-01],
       [-1.22988613e-01, -5.97064617e-01, -8.69851578e-01,
        -6.35324015e-01, -6.6